export default {
  "project-setup": "ติดตั้งและโครงสร้างโปรเจกต์",
  "data-layer": "Data Layer และข้อมูลตัวอย่าง",
  "app-router": "App Router และ Navigation",
  "server-client-components": "Server และ Client Components",
  "data-fetching": "การดึงข้อมูล",
  "route-handlers": "Route Handlers",
  "server-actions": "Form และ Server Actions",
  "rendering-cache": "Rendering และ Cache",
  "error-handling": "Error Handling",
  "metadata-optimization": "Metadata และ Optimization",
  "environment-security": "Environment และ Security",
  authentication: "ติดตั้ง Auth.js และ Session",
  register: "ลงทะเบียนผู้ใช้",
  "auth-authorization": "Authentication และ Authorization",
  deployment: "Build และ Deployment",
};
