export default {
  "mobile-flutter-overview": "Mobile และ Flutter",
  "install-setup": "ติดตั้งและตั้งค่าเครื่องมือ",
  "dart-for-flutter": "Dart สำหรับ Flutter",
  "dart-async": "Asynchronous Dart",
  "flutter-project-structure": "โครงสร้างโปรเจกต์ Flutter",
  "widgets-lifecycle": "Widget และ Lifecycle",
  "layouts-responsive": "Layout และ Responsive UI",
  "forms-theme-accessibility": "Form, Theme และ Accessibility",
  "navigation-routing": "Navigation และ Routing",
  "state-management": "State Management",
  "app-architecture": "Flutter App Architecture",
  "networking-rest-api": "Networking และ REST API",
  "local-storage": "Local Storage และ Offline Data",
  "authentication-firebase": "Authentication และ Firebase",
  "device-features": "Permission และ Device APIs",
  "testing-debugging-release": "Testing, Debugging และ Release",
};
