export default {
  "course-overview": "คำอธิบายรายวิชา",
  intro: "การเริ่มต้นและติดตั้ง",
  "expo-installation": "Installation with Expo",
  components: "Core Components",
  styling: "การจัดรูปแบบและ Styling",
  "components-style": "Components and Style",
  "expo-router": "Expo Router",
  "page-navigation": "Page and Navigation",
  "layouts-stack": "Layouts and Stack",
  navigation: "Navigation",
  "state-management": "State Management",
  "api-networking": "API และ Networking",
  storage: "Local Storage",
  camera: "Camera",
  "location-map": "Location and Map",
  "local-authentication": "Local Authentication",
  building: "Building with EAS",
  "course-project": "โปรเจกต์ประจำวิชา",
  workshop: "Workshop",
};
