export default {
  "course-overview": "ภาพรวมและคำอธิบายรายวิชา",
  "week-01": "สัปดาห์ 1 · Mobile, React Native และ Expo",
  "week-02": "สัปดาห์ 2 · Components, Props และ State",
  "week-03": "สัปดาห์ 3 · Styling และ Responsive UI",
  "week-04": "สัปดาห์ 4 · Expo Router และ Navigation",
  "week-05": "สัปดาห์ 5 · Forms และ State Management",
  "week-06": "สัปดาห์ 6 · REST API และ Networking",
  "week-07": "สัปดาห์ 7 · Storage และ Offline",
  "week-08": "สัปดาห์ 8 · Authentication และ Security",
  "week-09": "สัปดาห์ 9 · Camera, Image และ Permissions",
  "week-10": "สัปดาห์ 10 · Location และ Maps",
  "week-11": "สัปดาห์ 11 · Notifications และ Platform APIs",
  "week-12": "สัปดาห์ 12 · Architecture, Performance และ Accessibility",
  "week-13": "สัปดาห์ 13 · Testing และ Debugging",
  "week-14": "สัปดาห์ 14 · Build, Release และ Presentation",
  "course-project": "โปรเจกต์ Campus Events Mobile",
  workshop: "แบบฝึกเสริม · Todo App",

  // เก็บ URL เดิมไว้สำหรับลิงก์จากเอกสารเก่า แต่ไม่แสดงซ้ำในเส้นทางหลัก
  intro: { display: "hidden" },
  "expo-installation": { display: "hidden" },
  components: { display: "hidden" },
  styling: { display: "hidden" },
  "components-style": { display: "hidden" },
  "expo-router": { display: "hidden" },
  "page-navigation": { display: "hidden" },
  "layouts-stack": { display: "hidden" },
  navigation: { display: "hidden" },
  "state-management": { display: "hidden" },
  "api-networking": { display: "hidden" },
  storage: { display: "hidden" },
  camera: { display: "hidden" },
  "location-map": { display: "hidden" },
  "local-authentication": { display: "hidden" },
  building: { display: "hidden" },
};
